{
  "openapi": "2.0",
  "info": {
    "title": "test-api API",
    "description": "This API allows interaction with databse on create/delete/update users",
    "version": "v1"
  },
  "paths": {
    "/users": {
      "post": {
        "summary": "Creates a user",
        "tags": [
          "User"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "user",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                }
              },
              "required": [
                "name"
              ]
            }
          }
        ],
        "responses": {
          "201": {
            "description": "user created"
          }
        }
      },
      "get": {
        "summary": "List all users",
        "tags": [
          "Users"
        ],
        "consumes": [
          "application/json"
        ],
        "responses": {
          "201": {
            "description": "user created"
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "summary": "Retrieves a user",
        "tags": [
          "User"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "user found",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                }
              },
              "required": [
                "id"
              ]
            }
          },
          "404": {
            "description": "user not found"
          }
        }
      }
    }
  },
  "servers": [
    {
      "url": "https://damp-sierra-25855.herokuapp.com"
    }
  ]
}